/**:
  ros__parameters:
    jerk_weight: 10.0        # weight for "smoothness" cost for jerk
    #HJK_241208_B {
    over_v_weight: 10.0  # weight for "over speed limit" cost
    over_a_weight: 8.0    # weight for "over accel limit" cost
    over_j_weight: 5.0    # weight for "over jerk limit" cost
    #HJK_241208_B }
    jerk_filter_ds: 0.1      # resampling ds for jerk filter
